import {fonts} from "./_components/font"
import ChakraProvider from "./_components/chakra"
import HeaderFooter from "./_components/header-footer"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({children}) {
	return (
		<html lang="en" className={fonts.rubik.variable}>
			<body>
				<ChakraProvider>
					<HeaderFooter>{children}</HeaderFooter>
				</ChakraProvider>
			</body>
		</html>
	)
}
